# Generated by Django 3.1.2 on 2020-10-14 19:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20201014_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 14, 19, 7, 33, 416374, tzinfo=utc)),
        ),
    ]
