# Generated by Django 3.1.2 on 2020-10-14 19:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_item_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
